{
  # Generated by nix-autodep 1 on 2026-05-10 18:36 UTC
  # Command: go run .
  description = "Dev shell for: go run .";

  inputs = {
    nixpkgs = {
      url = "github:NixOS/nixpkgs/nixos-unstable";
    };
    flake-utils = {
      url = "github:numtide/flake-utils";
    };
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells = {
          default = pkgs.mkShell {
            buildInputs = [
              pkgs.go
            ];

            shellHook = ''
              echo "Environment ready (generated by nix-autodep)"
            '';
          };
        };
        packages = {
          default = pkgs.writeShellScriptBin "run" ''
            exec go run . "$@"
          '';
        };
      }
    );
}
